name: hypertrack_plugin
description: Flutter plugin for HyperTrack, a cross-platform location tracking solution for Android and iOS
repository: https://github.com/hypertrack/sdk-flutter
version: 0.4.3
homepage: https://www.hypertrack.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.hypertrack.sdk.flutter
        pluginClass: HyperTrackPlugin
      ios:
        pluginClass: HyperTrackPlugin
